### Get All Users with Pagination
GET http://localhost:3000/v1/users?offset=3&limit=3

### Filter Users by Name
GET http://localhost:3000/v1/users/byName/Amit

### Filter Users by Email Address
GET http://localhost:3000/v1/users/byEmail/Amit@example.com

### Update Users Statuses
PATCH http://localhost:3000/v1/users/updateStatuses
Content-Type: application/json

{
    "updates": [
        {
            "id": 1,
            "status": "active"
        },
        {
            "id": 2,
            "status": "active"
        },
        {
            "id": 3,
            "status": "active"
        },
        {
            "id": 4,
            "status": "active"
        }
    ]
}

### Remove user from group
PATCH http://localhost:3000/v1/users/10/removeGroupInfo