### byName
GET http://localhost:3000/v1/users/byName/a



### updateStatuses
PATCH http://localhost:3000/v1/users/updateStatuses
Content-Type: application/json

{
    "updates": [
        {
            "id": 1,
            "status": "active"
        },
        {
            "id": 2,
            "status": "active"
        },
        {
            "id": 3,
            "status": "active"
        },
        {
            "id": 4,
            "status": "active"
        }
    ]
}

### updateStatuses
PATCH http://localhost:3000/v1/users/10/removeGroupInfo